### ISSUE TITLE
Support UTF-8 in filenames

### ISSUE THREAD

**Issue by cxw42** [cxw42/editorconfig-core-vimscript#2]
... Although, per https://github.com/editorconfig/editorconfig-core-c/pull/31#issue-154810185, it may not be possible to do so on Windows.

**Comment by cxw42** [comment]
See https://github.com/editorconfig/editorconfig/issues/383#issuecomment-483578559 by @mcepl for a test failure on Linux.

**Comment by mcepl** [comment]
Sure, only after I pasted that monstrosity to the other bug I felt like an idiot. That was too long, but I wanted to be comprehensive.

**Comment by cxw42** [comment]
:) better more data than less!  I'm going to look through the code and and you a separate script trying a few different options.

**Comment by cxw42** [comment]
Looks like it may at least partly be a Unicode regex issue - https://vi.stackexchange.com/q/19616/1430

**Comment by mcepl** [comment]
```
100% tests passed, 0 tests failed out of 337
```
Thank you.

**Comment by cxw42** [comment]
@mcepl \o/  Is that with 63c86c32c550b8c4d6e0c2013271b708d22ef185?  That commit also passed on Appveyor (skipping UTF8 tests on Windows).

UTF-8 support turned out to be easier to add than I had thought it would.  However, it does currently assume that the value of `encoding` is correct for the filenames.  Do you have any experience using Vim with non-utf8 filenames?  E.g., cp852/cp912/cp1250 filenames?

**Comment by mcepl** [comment]
> @mcepl \o/ Is that with [63c86c3](https://github.com/cxw42/editorconfig-core-vimscript/commit/63c86c32c550b8c4d6e0c2013271b708d22ef185)? 

Yes.

Concerning encoding of file names, it is complete mess, which is IMHO unresolveable on the level of Vim, I believe. IIRC, no filesystem contains information about encoding of filenames, and (perhaps with exception of modern ones, like BTRFS, or ext4) no filesystem states what encoding filenames should be stored in. It is probably more consensus enforced by kernel, but I believe all Linux filesystems use UTF-8 for encoding filenames. When you get to the other filesystems (namely, VFAT filesystem on USB drive shared between Linux and Windows) you are in area of pure magic. Windows use their "DOS encoding" (remember, on Windows the mess is even worse, because every locale has two, not one encoding to care: for my Czech, we have windows-1250 for GUI, and cp852 for console and filesystem encoding), and the result is mess. Just take a look at [this search on DuckDuckGo](https://duckduckgo.com/?q=linux+vfat+file+names+encoding&t=ffab&ia=web) and cry. I think, the only possible thing to do (and what mostly all Linux programs do) is to ignore this whole mess and let the responsibility lie on the Linux admin to set correctly ``iocharset`` parameter and for everybody else just pray that it will work.

**Comment by cxw42** [comment]
Makes sense.  Then I think this can be closed!  Thanks again for testing!

**Comment by cxw42** [comment]
@mcepl I realized I hadn't updated the tests/ submodule to the latest.  I have now done so, and made some corresponding code fixes.  Would you please rerun with https://github.com/cxw42/editorconfig-core-vimscript/commit/4495efd89774045800931d8b3bad414de7c58d1e when you get a chance?  Once it passes in your environment, Appveyor, and my environments, I'll respond on the issue in the Vim repo.  Thank you!

**Comment by cxw42** [comment]
BTW

Appveyor image | time
-- | --
Image: Visual Studio 2013 | 17 min 43 sec
Image: Ubuntu1604 | 22 sec

o_O

**Comment by mcepl** [comment]
With 4495efd:
```
100% tests passed, 0 tests failed out of 337

Total Test time (real) =  22.57 sec
```
But I think the time is so much dependent on zillion other considerations (used hardware, current utilization of other virtual machines, etc.) that it is mostly irrelevant.
